#include <stdio.h>

#include <sys/stat.h>

#define FNAME "cast.5428E.txt.voc"

int main()
{             
FILE *fp;

unsigned long ulo;

struct stat fileStats;

	if (stat(FNAME, &fileStats) != 0)
	{

		printf("/* Can't stat file %s*/ \n", FNAME);

		return -2;

	}
	else
	{
		fp=fopen(FNAME,"r");

		if(NULL == fp)
		{
			printf("/* Some problem on FIRST opening the file %s*/ ", FNAME );

			return -1;
		} 
		else
		{ 
		int i;
		char c[512];

			printf("/* This is AUTOGENERATED file. Do NOT edit it. */\n");

			printf("\n#include \"constants.h\"\n");

			while ( !feof(fp) )
			{
				i++;

				fscanf(fp, "%s\n", &c);

				printf("/* Decl. of variable for %d%s keyword found in <%s> file */\n", i, (i==1)?"st":((i==2)?"nd":((i==3)?"rd":"th")), FNAME );

				printf("char %s [MAX_STR_SIZE];\n\n", &c);
			}
			fclose(fp);

			printf("/* End of AUTOGENERATed file */");
		}
	}

	return 0;  

}
